# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"

   config.vm.provision "shell", inline: <<-SHELL
     apt-get update
	 sudo apt install python3.9 -y
	 sudo apt install python3-pip -y
	 sudo apt-get install libpq-dev python-dev -y
	 sudo pip install psycopg2 -y
	 sudo apt install python3-django -y
   SHELL
   config.vm.provision "file", source: "./base", destination: "~/home"
end
